# Generated by Django 4.0.2 on 2022-04-07 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('Password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h_name', models.CharField(max_length=100, verbose_name='Hostel Name')),
                ('h_email', models.EmailField(max_length=100, verbose_name='Hostel Email')),
                ('h_contact', models.CharField(max_length=100, verbose_name='Hostel Contact')),
                ('h_city', models.CharField(max_length=30, null=True, verbose_name='City')),
                ('h_address', models.TextField(max_length=100, verbose_name='Hostel Address')),
                ('h_fees', models.IntegerField(null=True, verbose_name='Hostel Fees')),
                ('h_registered', models.DateTimeField(auto_now_add=True)),
                ('h_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.hadmin', verbose_name='Admin')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_no', models.IntegerField()),
                ('hostel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.hostel')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('contact', models.CharField(max_length=30)),
                ('hostel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.hostel')),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.room')),
            ],
        ),
    ]
